### ISSUE TITLE
I trained iris model by running provided Python code, but cannot be imported 

### ISSUE THREAD

**Issue by tofighi** [t-wolfeadam/AnyLogic-ONNX-Helper#8]
I used provided Python code for Iris on Google Colab [here](https://github.com/tofighi/AnyLogic/blob/main/iris2onnx.ipynb), and train the model, but the `iris.onnx` generated using Google Colab is not working and cause the following error. I am using [OnnxHelperLibrary.jar 2.1.1](https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/releases/download/v2.1.1/OnnxHelperLibrary.jar)

 Any solution for it?

<pre>
Error during model startup:
root.onnxHelper:
Failed to import ONNX model
Caused by: Error code - ORT_FAIL - message: Load model from /Users/sina/Documents/GitHub/tofighi/AnyLogic/BasicModels/Iris Prediction/iris.onnx failed:/Users/runner/work/1/s/onnxruntime/core/graph/model_load_utils.h:57 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::string, int> &, const logging::Logger &, bool, const std::string &, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 18 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 16.

java.lang.RuntimeException: root.onnxHelper:
Failed to import ONNX model
	at com.anylogic.engine.Engine.error(Unknown Source)
	at com.anylogic.engine.Agent.error(Unknown Source)
	at onnx_wrapper.OnnxHelper.reloadSession(OnnxHelper.java:235)
	at onnx_wrapper.OnnxHelper.onStartup(OnnxHelper.java:1062)
	at com.anylogic.engine.Agent.f(Unknown Source)
	at com.anylogic.engine.Agent.f(Unknown Source)
	at com.anylogic.engine.Agent.start(Unknown Source)
	at com.anylogic.engine.Engine.start(Unknown Source)
	at com.anylogic.engine.ExperimentSimulation.j(Unknown Source)
	at com.anylogic.engine.ExperimentSimulation.run(Unknown Source)
	at com.anylogic.engine.ExperimentSimulation.a(Unknown Source)
	at com.anylogic.engine.internal.e$e.run(Unknown Source)
Caused by: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Load model from /Users/sina/Documents/GitHub/tofighi/AnyLogic/BasicModels/Iris Prediction/iris.onnx failed:/Users/runner/work/1/s/onnxruntime/core/graph/model_load_utils.h:57 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::string, int> &, const logging::Logger &, bool, const std::string &, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 18 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 16.

	at ai.onnxruntime.OrtSession.createSession(Native Method)
	at ai.onnxruntime.OrtSession.<init>(OrtSession.java:71)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:222)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:208)
	at onnx_wrapper.OnnxHelper.reloadSession(OnnxHelper.java:232)
	... 9 more
</pre>

**Comment by t-wolfeadam** [comment]
Reading through the error message, most of it doesn't make sense to me but one part that caught my eye was the part about versioning...guessing it was related, I compared the ONNX version used by your collab, what the exported ONNX file was (in Netron), and what the ONNX Helper came with (pic below). 

![image](https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/assets/40703071/2b6852bd-64dc-4a74-a213-f22d2cf945f9)


It's kind of confusing, one because ONNX has different components with different version types and two because it seems to export in a version below the library's (i.e., opset v18 vs v19; unsure why). For point 1, fortunately ONNX provides [this lookup table](https://github.com/onnx/onnx/blob/main/docs/Versioning.md#released-versions). From looking at this, you can see that this library by default comes with v1.11/Opset v16 whereas your code exports using a later version.

Two solutions, I recommend trying them in sequential order:
**1.** Convert your model to use Opset v16 using ONNX's `onnx.version_converter.convert_version` function. Here is one way you can refactor your existing code to accommodate this:

```python
def save_to_onnx(model, filename, opset_version=None):
    """ Save a keras model as an ONNX file, optionally converting the version """
    proto = convert_keras(model)

    if opset_version:
      proto = onnx.version_converter.convert_version(proto, opset_version)

    if not filename.endswith(".onnx"): filename += ".onnx"
    onnx.save(proto, filename)

#Run and Save Model
model, score = train_pipeline(1, 8)
print("Score:", score)

save_to_onnx(model, "iris.onnx", 16)
```

**2.** Upgrade this library's ONNX version, [as described here](https://github.com/t-wolfeadam/AnyLogic-ONNX-Helper/wiki/Technical-Details#hardware-acceleration)
